spring:
  application:
    name: feign-retryable-example

server:
  port: 8081

logging:
  level:
    org:
      springframework:
        web:
          servlet:
            DispatcherServlet: INFO
    com.benjsoft.feignretryableexample: DEBUG

feign:
  client:
    config:
      default:
        loggerLevel: BASIC
        errorDecoder: com.benjsoft.feignretryableexample.ErrorDecoder
        #retryer: com.benjsoft.feignretryableexample.FeignRetryer
